$('.services-carusol').owlCarousel({
    loop:true,
    margin:10,
    rtl:true,
    dots:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:2,
            nav:true
        },
        1000:{
            items:3,
            nav:true,
            loop:true
        }
    }
})
$('.customer .owl-carousel').owlCarousel({
    loop:true,
    // margin:10,
    rtl:true,
    dots:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:true
        },
        1000:{
            items:4,
            nav:true,
            loop:true
        }
    }
})
// ////////////////////////////////////
